volumes:
  etc_wireguard:

services:
  next-guard:
    environment:
    - NEXTAUTH_SECRET= # openssl rand -base64 32
    - NEXTAUTH_URL= # public url
    build: .
    container_name: next-guard
    volumes:
      - ./database:/app/database
    ports:
      - "51820:51820/udp"
      - "3000:3000/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
